/**
 * gallery-data.tsx
 *
 * All static gallery content (categories + images) in one place.
 * Keeping data out of GalleryPage.tsx means the component file stays focused
 * on rendering logic while this file can be updated independently.
 */

import { Zap, Radio, Shovel, Building2 } from 'lucide-react';
import type { GalleryCategory } from './types';

export const galleryCategories: GalleryCategory[] = [
  {
    id: 'ev-charging',
    title: 'EV Charging Infrastructure',
    description: 'Electric vehicle charging station installations including trenching, conduit, and equipment deployment.',
    icon: <Zap className="w-6 h-6" />,
    color: 'from-green-500 to-emerald-600',
    images: [
      // Antioch, CA
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-20.webp', alt: 'EV charging station concrete pad installation', location: 'Antioch, CA', description: 'Concrete pad and bollard installation for commercial EV charger', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-1.webp', alt: 'Underground conduit trenching for EV station', location: 'Antioch, CA', description: 'Precision trenching for electrical conduit routing', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-3.webp', alt: 'EV station site work', location: 'Antioch, CA', description: 'Site preparation and ground work for charging infrastructure', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-4.webp', alt: 'Conduit layout planning', location: 'Antioch, CA', description: 'Conduit routing plan laid out prior to installation', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-7.webp', alt: 'Trench excavation for EV power lines', location: 'Antioch, CA', description: 'Trench excavation for high-voltage EV power supply', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-9.webp', alt: 'Conduit in trench', location: 'Antioch, CA', description: 'Conduit placed and ready for backfill', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-16.webp', alt: 'EV station electrical work', location: 'Antioch, CA', description: 'Electrical connections and wiring for charging equipment', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-17.webp', alt: 'EV charging equipment mounting', location: 'Antioch, CA', description: 'Level 2 charger equipment mounting and wiring', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-25.webp', alt: 'Electrical panel upgrade for EV charging', location: 'Antioch, CA', description: 'Service panel upgrade to support charging infrastructure', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-29.webp', alt: 'EV charger mounting hardware', location: 'Antioch, CA', description: 'Bollard and mounting hardware installation', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-31.webp', alt: 'Conduit installation in trench', location: 'Antioch, CA', description: 'Multiple conduit runs for power and communications', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-33.webp', alt: 'EV station trench work', location: 'Antioch, CA', description: 'Deep conduit trench for EV power feeds', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-39.webp', alt: 'Backfill and compaction', location: 'Antioch, CA', description: 'Proper backfill and soil compaction around infrastructure', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-41.webp', alt: 'EV charging station progress', location: 'Antioch, CA', description: 'Mid-project progress on multi-charger installation', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-43.webp', alt: 'Site restoration after trenching', location: 'Antioch, CA', description: 'Site surface restoration following conduit installation', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-45.webp', alt: 'EV charger wiring installation', location: 'Antioch, CA', description: 'Final wiring connections to EV charging units', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-49.webp', alt: 'EV station commissioning', location: 'Antioch, CA', description: 'Testing and commissioning of installed chargers', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-55.webp', alt: 'Completed EV charger installation', location: 'Antioch, CA', description: 'Finished EV charging unit ready for operation', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-61.webp', alt: 'EV station parking lot work', location: 'Antioch, CA', description: 'Parking lot integration for EV charging stations', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-66.webp', alt: 'EV station final inspection', location: 'Antioch, CA', description: 'Final walkthrough and safety inspection', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-71.webp', alt: 'EV charger close-up', location: 'Antioch, CA', description: 'Installed charger hardware and signage detail', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-76.webp', alt: 'EV charging station row', location: 'Antioch, CA', description: 'Row of completed EV charging stations', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/antioch-ca-ev-charging/antioch-ca-ev-charging-station-81.webp', alt: 'Completed EV charging project', location: 'Antioch, CA', description: 'Completed commercial EV charging site', category: 'EV Charging Infrastructure' },
      // Chemult, OR
      { src: '/images/projects/Oregon-AV-Station/AV-station/Oregon-AvStations-hero.jpg', alt: 'Completed EV charging station overview', location: 'Chemult, OR', description: 'DC fast charging station with multiple charging points', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation-parking-1.jpg', alt: 'EV charging parking layout', location: 'Chemult, OR', description: 'ADA-compliant charging station parking configuration', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation-parking-2.jpg', alt: 'EV charger with vehicle bay markings', location: 'Chemult, OR', description: 'Painted bay markings and charging station installation', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvAtation-parking-5.jpg', alt: 'EV station parking area', location: 'Chemult, OR', description: 'Completed parking area with EV charging infrastructure', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation-parking-6.jpg', alt: 'EV charging station row view', location: 'Chemult, OR', description: 'Row view of completed charging stations', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation-parking-7.jpg', alt: 'Charging station signage', location: 'Chemult, OR', description: 'Wayfinding and charging station identification signage', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation-parking-8.jpg', alt: 'EV station equipment detail', location: 'Chemult, OR', description: 'Charging equipment hardware and cable management', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation-parking-9.jpg', alt: 'EV charger installation detail', location: 'Chemult, OR', description: 'Close-up of installed EV charging unit connections', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation-parking-10.jpg', alt: 'EV charging site aerial view', location: 'Chemult, OR', description: 'Wide view of completed EV charging facility', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/AV-station/AvStation2.jpg', alt: 'EV charging station exterior', location: 'Chemult, OR', description: 'Exterior view of completed charging station facility', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Oregon-AV-Station/Av-Station-EV.jpg', alt: 'EV charging station full site', location: 'Chemult, OR', description: 'Full site view of the Chemult EV charging installation', category: 'EV Charging Infrastructure' },
      // Ripon, CA
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-1.webp', alt: 'Start of EV trench operation', location: 'Ripon, CA', description: 'Initial excavation with safety perimeter established', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-2.webp', alt: 'EV station trench in progress', location: 'Ripon, CA', description: 'Trench excavation advancing across the parking lot', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-4.webp', alt: 'Conduit layout in trench', location: 'Ripon, CA', description: 'Conduit positioning prior to burial', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-5.webp', alt: 'Conduit placement in trench', location: 'Ripon, CA', description: 'Rigid conduit installation with proper spacing', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-6.webp', alt: 'Trench conduit detail', location: 'Ripon, CA', description: 'Detailed view of conduit arrangement in trench', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-7.webp', alt: 'Trench near completion', location: 'Ripon, CA', description: 'Conduit installed, trench ready for backfill', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-8.webp', alt: 'Trench with warning tape', location: 'Ripon, CA', description: 'Caution tape marking for buried utilities', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-9.webp', alt: 'Backfill in progress', location: 'Ripon, CA', description: 'Trench backfill and surface restoration', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-10.webp', alt: 'Trench inspection', location: 'Ripon, CA', description: 'Quality inspection of conduit installation depth', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-11.webp', alt: 'EV trench near panel', location: 'Ripon, CA', description: 'Conduit routing approaching electrical panel', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-12.webp', alt: 'Trench section complete', location: 'Ripon, CA', description: 'Completed trench section with conduit in place', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-13.webp', alt: 'EV station trench wide view', location: 'Ripon, CA', description: 'Wide view of trenching operation across site', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-14.webp', alt: 'Final conduit burial', location: 'Ripon, CA', description: 'Final conduit burial before surface restoration', category: 'EV Charging Infrastructure' },
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-15.webp', alt: 'EV station trenching complete', location: 'Ripon, CA', description: 'Deep trench excavation for high-voltage conduit', category: 'EV Charging Infrastructure' },
    ],
  },
  {
    id: 'underground-utilities',
    title: 'Underground Utilities & Trenching',
    description: 'Underground utility installation, directional boring, trenching, and conduit systems.',
    icon: <Shovel className="w-6 h-6" />,
    color: 'from-amber-500 to-orange-600',
    images: [
      // Chemult, OR — full trench sequence
      { src: '/images/projects/Oregon-AV-Station/trench/trench-1.jpg', alt: 'Utility trenching excavation', location: 'Chemult, OR', description: 'Excavator performing precision trenching for utilities', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-2.jpg', alt: 'Trench open with conduit', location: 'Chemult, OR', description: 'Open trench with conduit run staged for installation', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-3.jpg', alt: 'Conduit in trench', location: 'Chemult, OR', description: 'Conduit placed in trench at correct depth', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-4.jpg', alt: 'Trench excavation progress', location: 'Chemult, OR', description: 'Continuous trench excavation for utility run', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-5.jpg', alt: 'Deep trench for conduit', location: 'Chemult, OR', description: 'Code-compliant depth for underground power lines', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-6.jpg', alt: 'Trench along site perimeter', location: 'Chemult, OR', description: 'Perimeter utility trench installation', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-7.jpg', alt: 'Multiple conduit installation', location: 'Chemult, OR', description: 'Parallel conduit runs for power and fiber', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-8.jpg', alt: 'Trench with bedding sand', location: 'Chemult, OR', description: 'Sand bedding installed below conduit for protection', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-9.jpg', alt: 'Trench at road crossing', location: 'Chemult, OR', description: 'Utility trench crossing at road transition point', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-10.jpg', alt: 'Trench backfill operation', location: 'Chemult, OR', description: 'Controlled backfill with compaction testing', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-11.jpg', alt: 'Trench nearing completion', location: 'Chemult, OR', description: 'Nearly complete trench run approaching panel location', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-12.jpg', alt: 'Utility corridor excavation', location: 'Chemult, OR', description: 'Wide utility corridor for multiple services', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-13.jpg', alt: 'Final trench section', location: 'Chemult, OR', description: 'Final trench section before site restoration', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/tench-14.jpg', alt: 'Trench backfill compaction', location: 'Chemult, OR', description: 'Compaction of backfill material in trench', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-15.jpg', alt: 'Site restoration after trenching', location: 'Chemult, OR', description: 'Surface restoration following conduit burial', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-16.jpg', alt: 'Completed utility run', location: 'Chemult, OR', description: 'Completed underground utility installation', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/trench-pipes.jpg', alt: 'Pipe manifold in trench', location: 'Chemult, OR', description: 'Multiple pipe manifold assembly in utility trench', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/trench/image18.jpg', alt: 'Underground work detail', location: 'Chemult, OR', description: 'Detail view of underground utility installation', category: 'Underground Utilities' },
      { src: '/images/projects/Oregon-AV-Station/site/site-1.jpg', alt: 'Project site overview', location: 'Chemult, OR', description: 'Overall site view showing scope of excavation work', category: 'Underground Utilities' },
      // Winnemucca, NV — full project
      { src: '/images/projects/Winnemucca-NV/trench-1.jpg', alt: 'Utility trench excavation', location: 'Winnemucca, NV', description: 'Trench excavation for underground utility installation', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-2.jpg', alt: 'Conduit placement in trench', location: 'Winnemucca, NV', description: 'Conduit positioned in trench prior to backfill', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-3.jpg', alt: 'Trench with conduit run', location: 'Winnemucca, NV', description: 'Conduit run extending across the job site', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-4.jpg', alt: 'Trench excavation progress', location: 'Winnemucca, NV', description: 'Progressing trench for underground power and communications', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-5.jpg', alt: 'Open trench detail', location: 'Winnemucca, NV', description: 'Detailed view of open trench and soil conditions', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-6.jpg', alt: 'Conduit in trench', location: 'Winnemucca, NV', description: 'Rigid conduit installed at proper depth', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-7.jpg', alt: 'Trench near road', location: 'Winnemucca, NV', description: 'Trench approaching road crossing with safety barricades', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-8.jpg', alt: 'Backfill operation', location: 'Winnemucca, NV', description: 'Backfill material being placed over installed conduit', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-9.jpg', alt: 'Compaction after backfill', location: 'Winnemucca, NV', description: 'Mechanical compaction of backfill to specified density', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-10.jpg', alt: 'Trench continuation', location: 'Winnemucca, NV', description: 'Continuing trench for extended utility run', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-11.jpg', alt: 'Utility trench progress', location: 'Winnemucca, NV', description: 'Mid-project progress of utility trench installation', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-12.jpg', alt: 'Trench nearing final section', location: 'Winnemucca, NV', description: 'Final trench section approaching termination point', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-14.jpg', alt: 'Surface restoration', location: 'Winnemucca, NV', description: 'Surface restoration work following conduit burial', category: 'Underground Utilities' },
      { src: '/images/projects/Winnemucca-NV/trench-15.jpg', alt: 'Completed underground utility', location: 'Winnemucca, NV', description: 'Project complete with surface fully restored', category: 'Underground Utilities' },
      // Ripon, CA
      { src: '/images/projects/Ripon-CA/ripon-ev-station-trench-3.webp', alt: 'Conduit in open trench', location: 'Ripon, CA', description: 'PVC conduit placement before backfill', category: 'Underground Utilities' },
      // Bodega Bay, CA
      { src: '/images/projects/Bodega-Bay-CA/trench-1.jpg', alt: 'Site trenching for utilities', location: 'Bodega Bay, CA', description: 'Trenching for water and electrical services', category: 'Underground Utilities' },
      { src: '/images/projects/Bodega-Bay-CA/trench-2.jpg', alt: 'Underground pipe installation', location: 'Bodega Bay, CA', description: 'Utility pipe installation and bedding', category: 'Underground Utilities' },
      { src: '/images/projects/Bodega-Bay-CA/trench-3.jpg', alt: 'Completed utility trench', location: 'Bodega Bay, CA', description: 'Trench ready for inspection and backfill', category: 'Underground Utilities' },
      { src: '/images/projects/Bodega-Bay-CA/bulldozer-trench.jpg', alt: 'Bulldozer opening trench', location: 'Bodega Bay, CA', description: 'Bulldozer cutting initial trench path through site', category: 'Underground Utilities' },
    ],
  },
  {
    id: 'telecommunications',
    title: 'Telecommunications & Towers',
    description: 'Cell tower installation, telecommunications infrastructure, and network equipment deployment.',
    icon: <Radio className="w-6 h-6" />,
    color: 'from-blue-500 to-indigo-600',
    images: [
      { src: '/images/projects/Sparks-NV/tower-tree-7.jpg', alt: 'Completed stealth tree cell tower', location: 'Sparks, NV', description: 'Finished mono-pine stealth tower blending with landscape', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-tree-1.jpg', alt: 'Tower assembly in progress', location: 'Sparks, NV', description: 'Stealth tower section assembly and rigging', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-tree-2.jpg', alt: 'Tower sections staged for lift', location: 'Sparks, NV', description: 'Tower sections rigged and ready for crane lift', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-tree-install.jpg', alt: 'Crane lifting tower section', location: 'Sparks, NV', description: 'Precision crane operation for tower section placement', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-tree-3.jpg', alt: 'Tower branch installation', location: 'Sparks, NV', description: 'Decorative branch installation for stealth appearance', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-tree-4.jpg', alt: 'Telecommunications equipment installation', location: 'Sparks, NV', description: 'Installation of telecommunications hardware on tower', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-tree-6.jpg', alt: 'Tower exterior with branches', location: 'Sparks, NV', description: 'Completed exterior camouflage branch installation', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-base-1.jpg', alt: 'Tower concrete foundation', location: 'Sparks, NV', description: 'Reinforced concrete foundation with anchor bolts', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tower-base.jpg', alt: 'Tower base structure', location: 'Sparks, NV', description: 'Base structure and equipment shelter installation', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tree-tower-network.jpg', alt: 'Network equipment shelter', location: 'Sparks, NV', description: 'Ground-level equipment cabinet and power systems', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tree-tower.jpg', alt: 'Stealth tower mid-construction', location: 'Sparks, NV', description: 'Mid-construction view of stealth cell tower', category: 'Telecommunications' },
      { src: '/images/projects/Sparks-NV/tree-post.jpg', alt: 'Tower post installation', location: 'Sparks, NV', description: 'Main post installation before exterior cladding', category: 'Telecommunications' },
    ],
  },
  {
    id: 'site-development',
    title: 'Site Development & Grading',
    description: 'Commercial site preparation, excavation, grading, and heavy equipment operations.',
    icon: <Building2 className="w-6 h-6" />,
    color: 'from-purple-500 to-violet-600',
    images: [
      // Bodega Bay, CA
      { src: '/images/projects/Bodega-Bay-CA/construction-dozer.jpg', alt: 'Bulldozer site grading', location: 'Bodega Bay, CA', description: 'Heavy grading for commercial pad preparation', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/bulldozer-1.jpg', alt: 'Bulldozer pushing grade', location: 'Bodega Bay, CA', description: 'Bulldozer establishing rough grade on site', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/bulldozer-2.jpg', alt: 'Excavation operations', location: 'Bodega Bay, CA', description: 'Cut and fill operations for level building pad', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/bulldozer-3.jpg', alt: 'Site clearing', location: 'Bodega Bay, CA', description: 'Vegetation clearing and topsoil removal', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/bulldozer-4.jpg', alt: 'Grade establishment', location: 'Bodega Bay, CA', description: 'Final grade establishment per engineering plans', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/transport-1.jpg', alt: 'Flatbed equipment transport', location: 'Bodega Bay, CA', description: 'Specialized transport for construction equipment', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/transport-2.jpg', alt: 'Equipment offloading', location: 'Bodega Bay, CA', description: 'Safe equipment offloading procedures at site', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/case-1.jpg', alt: 'Compact track loader on site', location: 'Bodega Bay, CA', description: 'Versatile compact equipment for tight access areas', category: 'Site Development' },
      { src: '/images/projects/Bodega-Bay-CA/jack-hammer.jpg', alt: 'Jackhammer work detail', location: 'Bodega Bay, CA', description: 'Jackhammer breaking concrete for utility access', category: 'Site Development' },
      // General
      { src: '/images/projects/construction-site-1.jpg', alt: 'Construction site overview', location: 'California', description: 'Active construction site with equipment and crew', category: 'Site Development' },
      { src: '/images/projects/construction-site-2.jpg', alt: 'Site grading progress', location: 'California', description: 'Grading progress during active construction phase', category: 'Site Development' },
      { src: '/images/projects/construction-site-3.jpg', alt: 'Site preparation work', location: 'California', description: 'Site preparation and ground work for new development', category: 'Site Development' },
      { src: '/images/projects/TractorConcrete.jpg', alt: 'Tractor at concrete work', location: 'California', description: 'Equipment supporting concrete operations on site', category: 'Site Development' },
      { src: '/images/projects/transport-hero.jpg', alt: 'Equipment transport on highway', location: 'California', description: 'Heavy equipment transport between project sites', category: 'Site Development' },
    ],
  },
];

/** Flattened list of all images, used by the "All Projects" filter view. */
export const allImages = galleryCategories.flatMap((cat) => cat.images);
